"""Public Python API for Retrieval Lab."""

from retrieval_lab.chunkers import FixedSizeChunker
from retrieval_lab.config import (
    BM25RetrieverConfig,
    ChunkerConfig,
    CorpusConfig,
    DatasetConfig,
    DenseRetrieverConfig,
    EvaluationConfig,
    ExperimentConfig,
    HybridRetrieverConfig,
    KeywordRetrieverConfig,
    QualityGateConfig,
    ReportConfig,
    RetrievalConfig,
    load_config,
)
from retrieval_lab.datasets import EvaluationDataset, RelevanceLevel, validate_dataset
from retrieval_lab.domain import (
    Chunk,
    Document,
    EvaluationQuery,
    EvaluationResult,
    LatencyStats,
    QueryEvaluation,
    RetrieverMetrics,
    SearchResult,
)
from retrieval_lab.evaluation.precomputed import RetrievedQueryResult, evaluate_results
from retrieval_lab.exceptions import (
    ConfigurationError,
    CorpusValidationError,
    DatasetValidationError,
    EvaluationError,
    IncomparableRunError,
    OptionalDependencyError,
    RetrievalLabError,
    RetrieverContractError,
)
from retrieval_lab.loaders import load_documents
from retrieval_lab.retrievers import (
    BaseRetriever,
    BM25Retriever,
    CallableRetriever,
    DenseRetriever,
    EmbeddingBackend,
    EmbeddingModelMetadata,
    HybridRetriever,
    KeywordRetriever,
    RetrievedItem,
    Retriever,
    evaluate_retrievers,
)
from retrieval_lab.runner import EvaluationRunner

__all__ = [
    "BM25Retriever",
    "BM25RetrieverConfig",
    "BaseRetriever",
    "CallableRetriever",
    "Chunk",
    "ChunkerConfig",
    "ConfigurationError",
    "CorpusConfig",
    "CorpusValidationError",
    "DatasetConfig",
    "DatasetValidationError",
    "DenseRetriever",
    "DenseRetrieverConfig",
    "Document",
    "EmbeddingBackend",
    "EmbeddingModelMetadata",
    "EvaluationConfig",
    "EvaluationDataset",
    "EvaluationError",
    "EvaluationQuery",
    "EvaluationResult",
    "EvaluationRunner",
    "ExperimentConfig",
    "FixedSizeChunker",
    "HybridRetriever",
    "HybridRetrieverConfig",
    "IncomparableRunError",
    "KeywordRetriever",
    "KeywordRetrieverConfig",
    "LatencyStats",
    "OptionalDependencyError",
    "QualityGateConfig",
    "QueryEvaluation",
    "RelevanceLevel",
    "ReportConfig",
    "RetrievalConfig",
    "RetrievalLabError",
    "RetrievedItem",
    "RetrievedQueryResult",
    "Retriever",
    "RetrieverContractError",
    "RetrieverMetrics",
    "SearchResult",
    "evaluate_results",
    "evaluate_retrievers",
    "load_config",
    "load_documents",
    "validate_dataset",
]
