"""Public Python API for Retrieval Lab."""

from retrieval_lab.application import (
    ComparisonOutput,
    ComparisonRow,
    ExperimentOutput,
    GateOutput,
    InitializedProject,
    InspectionOutput,
    QueryEvidence,
    ValidationResult,
    compare_result_files,
    evaluate_configured_quality_gates,
    initialize_project,
    inspect_result,
    run_configured_experiment,
    validate_config_inputs,
)
from retrieval_lab.artifacts.results import load_result
from retrieval_lab.chunkers import FixedSizeChunker
from retrieval_lab.comparison import (
    ComparabilityIssue,
    ComparabilityReport,
    ComparisonTolerance,
    MetricComparison,
    MetricDelta,
    QueryDeltaExtreme,
    RunComparison,
    check_comparability,
    compare_runs,
)
from retrieval_lab.config import (
    BM25RetrieverConfig,
    ChunkerConfig,
    CorpusConfig,
    DatasetConfig,
    DenseRetrieverConfig,
    EvaluationConfig,
    ExperimentConfig,
    HybridRetrieverConfig,
    KeywordRetrieverConfig,
    QualityGateConfig,
    ReportConfig,
    RetrievalConfig,
    load_config,
)
from retrieval_lab.dataset_inspection import (
    DatasetInspectionCode,
    DatasetInspectionIssue,
    DatasetInspectionReport,
    inspect_dataset,
)
from retrieval_lab.datasets import EvaluationDataset, RelevanceLevel, validate_dataset
from retrieval_lab.domain import (
    Chunk,
    ConstraintType,
    Document,
    EvaluationQuery,
    EvaluationResult,
    LatencyStats,
    QualityGateCheck,
    QualityGateReport,
    QualityGateResult,
    QueryEvaluation,
    RetrieverMetrics,
    SearchResult,
)
from retrieval_lab.evaluation.precomputed import RetrievedQueryResult, evaluate_results
from retrieval_lab.exceptions import (
    ConfigurationError,
    CorpusValidationError,
    DatasetValidationError,
    EvaluationError,
    IncomparableRunError,
    OptionalDependencyError,
    RetrievalLabError,
    RetrieverContractError,
)
from retrieval_lab.loaders import load_documents
from retrieval_lab.quality import evaluate_quality_gates
from retrieval_lab.retrievers import (
    AsyncCallableRetriever,
    AsyncRetriever,
    BaseRetriever,
    BM25Retriever,
    CallableRetriever,
    DenseRetriever,
    EmbeddingBackend,
    EmbeddingModelMetadata,
    HybridRetriever,
    KeywordRetriever,
    RetrievedItem,
    Retriever,
    evaluate_async_retrievers,
    evaluate_retrievers,
)
from retrieval_lab.runner import EvaluationRunner

__all__ = [
    "AsyncCallableRetriever",
    "AsyncRetriever",
    "BM25Retriever",
    "BM25RetrieverConfig",
    "BaseRetriever",
    "CallableRetriever",
    "Chunk",
    "ChunkerConfig",
    "ComparabilityIssue",
    "ComparabilityReport",
    "ComparisonOutput",
    "ComparisonRow",
    "ComparisonTolerance",
    "ConfigurationError",
    "ConstraintType",
    "CorpusConfig",
    "CorpusValidationError",
    "DatasetConfig",
    "DatasetInspectionCode",
    "DatasetInspectionIssue",
    "DatasetInspectionReport",
    "DatasetValidationError",
    "DenseRetriever",
    "DenseRetrieverConfig",
    "Document",
    "EmbeddingBackend",
    "EmbeddingModelMetadata",
    "EvaluationConfig",
    "EvaluationDataset",
    "EvaluationError",
    "EvaluationQuery",
    "EvaluationResult",
    "EvaluationRunner",
    "ExperimentConfig",
    "ExperimentOutput",
    "FixedSizeChunker",
    "GateOutput",
    "HybridRetriever",
    "HybridRetrieverConfig",
    "IncomparableRunError",
    "InitializedProject",
    "InspectionOutput",
    "KeywordRetriever",
    "KeywordRetrieverConfig",
    "LatencyStats",
    "MetricComparison",
    "MetricDelta",
    "OptionalDependencyError",
    "QualityGateCheck",
    "QualityGateConfig",
    "QualityGateReport",
    "QualityGateResult",
    "QueryDeltaExtreme",
    "QueryEvaluation",
    "QueryEvidence",
    "RelevanceLevel",
    "ReportConfig",
    "RetrievalConfig",
    "RetrievalLabError",
    "RetrievedItem",
    "RetrievedQueryResult",
    "Retriever",
    "RetrieverContractError",
    "RetrieverMetrics",
    "RunComparison",
    "SearchResult",
    "ValidationResult",
    "check_comparability",
    "compare_result_files",
    "compare_runs",
    "evaluate_async_retrievers",
    "evaluate_configured_quality_gates",
    "evaluate_quality_gates",
    "evaluate_results",
    "evaluate_retrievers",
    "initialize_project",
    "inspect_dataset",
    "inspect_result",
    "load_config",
    "load_documents",
    "load_result",
    "run_configured_experiment",
    "validate_config_inputs",
    "validate_dataset",
]
